### ISSUE TITLE
Selected/Controlled Token alternates between owned tokens when not in combat.

### ISSUE THREAD

**Issue by Silidus** [skepickle/foundryvtt-gaming-table-player#11]
When not in combat, selected token and visuals alternate between owned tokens.

Suggest using the following
```
static async gamingTablePlayerLoop(){
		if (game.user.name != game.settings.get('gaming-table-player','player')) {
			//This should never be reached but try to catch it anyways.
			console.log("NOT GAMING TABLE PLAYER: "+ game.settings.get('gaming-table-player','player'));
			return;
		}
		if (game.settings.get('gaming-table-player','selecttokens')) {
			let in_combat = false;
			let in_combat_id = null;
			for (let i = 0; i < game.combats.apps.length; i++) {
				if ((game.combats.apps[i]) && (game.combats.apps[i].combats[0]).active) {
					for (let j = 0; j < canvas.tokens.ownedTokens.length; j++) {
						if (canvas.tokens.ownedTokens[j].id == game.combats.apps[i].combats[0].current.tokenId) {
							in_combat = true;
							in_combat_id = game.combats.apps[i].combats[0].current.tokenId;
						}
					}
				}
			}
            if (in_combat == false)
		{
			canvas.activeLayer.selectObjects(canvas.tokens.ownedTokens, {releaseOthers: true});
            }
            if (in_combat == true)
		{
			canvas.activeLayer.selectObjects({}, {releaseOthers: true});
			for (let i = 0; i < canvas.tokens.ownedTokens.length; i++) {
				if ((in_combat_id == null) || (in_combat_id == canvas.tokens.ownedTokens[i].id)) {
					canvas.tokens.ownedTokens[i].control({releaseOthers: false});
					//console.log("GAME TABLE : "+canvas.tokens.ownedTokens[i].name);
				}
			}
            }
            
		}
		//console.log("setTimeout!! " + game.settings.get('gaming-table-player','intervalspeed'))
		setTimeout(function() {
			GamingTablePlayer.gamingTablePlayerLoop();
		}, game.settings.get('gaming-table-player','intervalspeed'));
	}
```

**Comment by skepickle** [comment]
@Silidus what version of FoundryVTT did you see this bug with? And what version of the module are you running?

**Comment by skepickle** [comment]
I'm not seeing the described behavior in FoundryVTT v10.291 and gaming-table-player v1.0.2.

**Comment by skepickle** [comment]
I just released 1.0.3 that fixed an unrelated issue. Can you try to update and let me know if you are still seeing the alternating selection when out of combat?

**Comment by ghost** [comment]
I might have the same issue. I'm not in combat, but have the spectator account as an owner for my 5 party members. I put the refresh time down to 1000 ms to visualise what happens. It seems to be rotating through the selections. 
The first time it has the claimed token selected, then it selects another token, lastly it selects all the owned tokens, then it deselects. latest foundry and latest gaming table player.

**Comment by skepickle** [comment]
That's very good input. If anyone could provide info on the versions of Foundry itself and the module, that would help me track this issue down...

**Comment by Silidus** [comment]
I'll try to give a full trace and versions tomorrow, I fixed it in my local
version with the code in the ticket (though there is a bug in the combat
check iirc).

**Comment by skepickle** [comment]
Yeah, but the code you posted seems to be edits of vary old code... so I don't know if I want to take it as-is... I do however want to implement a fix that addresses this issue.

**Comment by skepickle** [comment]
If you could update to 1.0.3 and see if it still happens, that would be the most helpful.

**Comment by Silidus** [comment]
Original Issue observed in 0.0.8 and 1.0.3
Foundry version 10, build 291


Case 1:
Initial state:  VTT player has ownership of multiple characters scene in
different locations.

   - Characters are not in combat.


Observed Behavior: Each 'gamingTablePlayerLoop' selects a different actor
as the focus, causing view to alternate between visible characters
Expected Behaviour: All owned characters should be selected.

[image: image.png]
line 69 releases selected objects.

On next gamingTablePlayerLoop, a different owned character is selected.
[image: image.png]


Issue appears to be the difference between use of
canvas.activeLayer.selectedObjects on line 69, and
canvas.tokens.ownedTokens.control on line 83.


Case 2:

   - Two characters owned by VTT are placed in combat.

Exception thrown on line 72 retrieving Token ID
[image: image.png]

In this case 't' is null (combat not yet started by GM)

Case 3:

   - Two characters owned by VTT are placed in combat.
   - One NPC owned by GM in the same combat.
   - Combat is begun (owned characters turn).

This case appears to work correctly.  Focus stays on the actor owned by the
VTT player whose turn it is in the current combat round.


Case 4:

   - Two characters owned by VTT are placed in combat.
   - One NPC owned by GM in the same combat.
   - Combat is begun.
   - NPC not owned by VTT has current turn.

[image: image.png]

Identical to Case 1.  canvas.tokens.ownedTokens[i].control selects the last
token each pass, alternating vision among all actors owned by VTT.

**Comment by skepickle** [comment]
Can you please send me what the gaming-table-player.js file looks like for you as installed by the module? The line numbers don't match up with what I'm expecting in 1.0.3.

I'm also wondering if the system being used might come into play here. Could you tell me what gaming system you are using?

**Comment by skepickle** [comment]
Okay. I'm finally testing using 5e... it would seem that the system I was using had some stuff going on that were making things just super happy on my side. working on it now.

**Comment by skepickle** [comment]
Oh man! Okay, I fixed it completely differently. It had to do with arrays! ARRAYS! Anyways. Please check out release 1.0.4, and let me know if it's working better now.

**Comment by ghost** [comment]
Awesome! Updated and it works :D Thanks for the speedy fix. Is there a downside to setting it to 1000 ms instead of 5000?

**Comment by skepickle** [comment]
It's just the polling period... it could create excess CPU usage on the browser that the gaming-table-player is logged in on. But 1000ms shouldn't be too bad. :shrug:

**Comment by ghost** [comment]
Thanks for the explanation!
