### ISSUE TITLE
Hotkey doesn't seem to work.

### ISSUE THREAD

**Issue by OregonPinkRose** [skepickle/foundryvtt-gaming-table-player#12]
I can't seem to get this to work. I see options for it, but nothing I try gets it to move and copy the DMs screen.

**Comment by skepickle** [comment]
Can please provide the FoundryVTT version, and your system version? Also, do you have the gaming-table player setup? The hotkey is only supposed to recenter the gaming table player's view, at the location that the GM is pointing to with their mouse, as long as the gaming table player is viewing the same scene. Also, the zoom level will not be copied from the GM user, rather it will use the zoom level specified in the module settings.

**Comment by OregonPinkRose** [comment]
Oh, I wasn't using it correctly then. Thank you for helping me.
