### ISSUE TITLE
Interacts poorly with other modules causing players to lose token selection after a few seconds

### ISSUE THREAD

**Issue by GambetTV** [skepickle/foundryvtt-gaming-table-player#2]
This isn't an exhaustive list, but I've noticed that if Gaming Table Player is active, and the modules "Pings" and/or "Quick Insert" are also active, players connected through their browser won't be able to keep their token selected for more than a few seconds. If you remove both of those other modules then this works fine, but I suspect this is the problem module as if I remove this one, the other two can remain active and it's fine.

**Comment by skepickle** [comment]
@GambetTV could you share the configuration values for the module, under Configure Settings -> Module Settings -> Gaming Table Player?

**Comment by skepickle** [comment]
@GambetTV I would be interested to find out if you are having the same issues with version 0.0.2 of this module.

**Comment by skepickle** [comment]
I've installed and enabled both the 'Ping' and 'Quick Insert' modules, and I am unable to reproduce this error.
