### ISSUE TITLE
Draw rectangle on GM's view to indicate bounds of table view

### ISSUE THREAD

**Issue by skepickle** [skepickle/foundryvtt-gaming-table-player#25]
Implement this drawing based on implementation in PR #21, submitted by @misthero.

**Comment by skepickle** [comment]
The implementation of this in PR #21 puts the bounding box onto `canvas.stage`, which seems to be shown on every scene. I'm trying to figure out a better way to do this so that it's specific to the actual scene being shown on the gaming table and isn't displayed on other scenes.

**Comment by misthero** [comment]
yep that is a basic implementation,you just need to hide it from canvas if
the vtt character is on different scene,or if the scene the gm is looking
at is not the current active scene. you could just change its visibility
property to false.

also it lacks a method to remove the rectangle if the vtt player is
disconnected.

**Comment by skepickle** [comment]
@misthero checkout the Draft PR #27... I think I've made a clean solution, but let me know if you have any suggestions.

**Comment by misthero** [comment]
yes, I think that removing the layer children and not adding again based on the right condition should work too. not tested, but the code looks right.
