### ISSUE TITLE
Could you add a variable zoom?

### ISSUE THREAD

**Issue by GambetTV** [skepickle/foundryvtt-gaming-table-player#3]
Right now the zoom is set to a default level that you can never change from. Would it be possible to add a way to vary the zoom level on the fly? Like maybe if while holding down 't' you scroll the mouse wheel? Or perhaps just an option to let the zoom level equal that of the GM's zoom level? Either would be amazing!

**Comment by skepickle** [comment]
I'm afraid I can't accept this as a function that should be part of this module, based on the design-intent.
