### ISSUE TITLE
Panning animation gone

### ISSUE THREAD

**Issue by misthero** [skepickle/foundryvtt-gaming-table-player#32]
I noticed that the latest implementation lost the graceful animated pannig when the key to move VTT view is pressed. Not a bug but it was more pleasant before, also it allow players to understand better where they are moving on the map.

**Comment by skepickle** [comment]
Ah.. At some point I switched from using canvas.animatePan() to canvas.pan() because a Hook on canvasPan was causing a feedback loop. I'll look into whether I can revert this or not.
