### ISSUE TITLE
Keypress on chat or any other input field cause the screen to pan.

### ISSUE THREAD

**Issue by misthero** [skepickle/foundryvtt-gaming-table-player#34]
the Hotkey to move the VTT screen "t" by default, but it happens with every other key, is not ignored when you write in the chat, in a journal or any other input field. If you happen to write a word with the "t" letter in it, the VTT screen should not pan.

https://github.com/skepickle/foundryvtt-gaming-table-player/assets/3662610/9ae90788-4561-4f84-9242-b31338138e64

**Comment by skepickle** [comment]
The default hotkey has been changed to CTRL+ALT+SHIFT+T in the latest release. It should have always been set to some key sequence that is not common... It was a mistake previously to default to just 't'. That being said, I'll see if I can determine that the focus is on the map before changing the view.. not sure how to do that right now

**Comment by misthero** [comment]
this could be solved like this anyway: 

```
if (bind && game.user.isGM && overCanvas
		&& e.target.tagName.toUpperCase() != "INPUT" &&
		e.target.tagName.toUpperCase() != "TEXTAREA") 
```

**Comment by skepickle** [comment]
I'm switching to using game.keybindings.register() instead of continuing to reinvent the wheel in vanilla javascript ;-)

Please look at PR #35 and let me know what you think.
