### ISSUE TITLE
Please Update Version Number

### ISSUE THREAD

**Issue by CasualTerror** [skepickle/foundryvtt-gaming-table-player#4]
Can you please update the version number so hosting sites like Forge.VTT doesn't pull an outdated version?

**Comment by skepickle** [comment]
@CasualTerror I'm not sure what the requirements for Forge.VTT is, but I've just published version 0.0.2 of this module that fixes the issue with the hotkey not being configurable. I would love some feedback on whether or not this update fixes the issue you are seeing.

**Comment by skepickle** [comment]
I've updated the version. If there's still a problem, please feel free to open a new issue.
