### ISSUE TITLE
Not working in Foundry v10 due to settings-extender bug

### ISSUE THREAD

**Issue by LeRatierBretonnien** [skepickle/foundryvtt-gaming-table-player#5]
Easy to test : enable the module and try to open settings -> not working

**Comment by skepickle** [comment]
I am going to make the gaming-table-player module use the settings-extender module as a dependency. This should avoid this type of issue in the future.

**Comment by skepickle** [comment]
@sladecraven Does release 0.0.7 of gaming-table-player resolve your issue? I know that I have it setup still to be compatible through v9. But if the settings-extender module is updated to the version that resolves the bug in question, I think that should resolve it? Please let me know.

Basically 0.0.7 doesn't have a local copy of the settings-extender source code anymore... it's just got it setup as a dependency in the module.json.

FYI: I haven't actually upgraded my FVTT instances to v10 yet so I might not be able to test things myself.

**Comment by LeRatierBretonnien** [comment]
Hi ! Yes, tested and it works :) !
Thanks !

**Comment by skepickle** [comment]
Awesome! If it works, I think I'll actually push another commit to extend the compatibility in module.json up to v10.

**Comment by skepickle** [comment]
Okay. `0.0.8` has been published.
